
name: CI

# CONTROLS WHEN THE WORKFLOW WILL RUN
on:
# TRIGGERS WORKFLOW ON PUSH OR PR EVENTS ONLY FOR THE MAIN BRANCH
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # ALLOWS TO RUN THE WORKFLOW MANUALLY FROM ACTIONS TAB
  workflow_dispatch:

# A WORKFLOW RUN IS MADE UP OF ONE OR MORE JOBS THAT CAN RUN SEQUENTIALLY OR IN PARALLEL
jobs:

  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: checkout
        uses: actions/checkout@v3

      # AUTO-INCREMENTAL TAG
      - name: Get Latest Tag
        id: get_latest
        run: |
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          if [[ -z "$latest_tag" ]]; then
            latest_tag="0.0.0"
          fi
          echo "Latest tag: $latest_tag"
          echo "latest=$latest_tag" >> $GITHUB_ENV

      - name: Bump Version
        id: bump_version
        run: |
          IFS='.' read -r -a parts <<< "$latest"
          patch=$((parts[2] + 1))
          new_tag="${parts[0]}.${parts[1]}.$patch"
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Create New Tag
        run: |
          git tag $new_tag
          git push origin $new_tag
          git push --tags
      # END AUTO-INCREMENTAL TAG
      
      - name: Godot Export
        id: export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
          relative_project_path: ./
          presets_to_export: "Web"
          archive_output: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}

      - name: create release
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ env.new_tag }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
    
